// DO NOT MODIFY
// Automatically generated by SecretKeys (https://github.com/simorgh3196/swift-secret-keys)

import Foundation
import SecretValueDecoder

public enum ReleaseKeys {
    static let decoder = SecretValueDecoder()
}