// DO NOT MODIFY
// Automatically generated by SecretKeys (https://github.com/simorgh3196/swift-secret-keys)

import SecretKeysProduction

public struct KeysInRelease {
    static var clientID: Int { MySecretKeys.clientID }
    static var clientSecret: String { MySecretKeys.clientSecret }
    static var timeout: Double { MySecretKeys.timeout }
}
