// swift-tools-version: 5.6

// DO NOT MODIFY
// Automatically generated by SecretKeys (https://github.com/simorgh3196/swift-secret-keys)

import PackageDescription

let package = Package(
    name: "SecretKeys",
    platforms: [
        .iOS(.v11),
        .macOS(.v11),
        .tvOS(.v11),
        .watchOS(.v4),
    ],
    products: [
        .library(name: "SecretKeysDebug", targets: ["SecretKeysDebug"]),
        .library(name: "SecretKeysProduction", targets: ["SecretKeysProduction"]),
    ],
    targets: [
        .target(name: "SecretKeysDebug", dependencies: ["SecretValueDecoder"]),
        .target(name: "SecretKeysProduction", dependencies: ["SecretValueDecoder"]),

        .target(name: "SecretValueDecoder", path: "Sources/SecretValueDecoder"),
    ]
)