// DO NOT MODIFY
// Automatically generated by SecretKeys (https://github.com/simorgh3196/swift-secret-keys)

public struct KeysInDebug {
    static var clientID: Int { DebugKeys.clientID }
    static var clientSecret: String { DebugKeys.clientSecret }
    static var timeout: Double { DebugKeys.timeout }
}
