// DO NOT MODIFY
// Automatically generated by SecretKeys (https://github.com/simorgh3196/swift-secret-keys)

import SecretKeysProduction

public struct KeysInRelease {
    static var clientID: Int { ReleaseKeys.clientID }
    static var clientSecret: String { ReleaseKeys.clientSecret }
    static var timeout: Double { ReleaseKeys.timeout }
}
