// The MIT License (MIT)
//
// Copyright (c) 2022 Tomoya Hayakawa (github.com/simorgh3196).

import Foundation

enum PackageCodeGenerator {
    static func generateCode(projectName: String, withUnitTest: Bool) -> String {
        """
        // swift-tools-version: 5.7

        // DO NOT MODIFY
        // Automatically generated by SecretKeys (https://github.com/simorgh3196/SecretKeys)

        import PackageDescription

        let package = Package(
            name: "\(projectName)",
            platforms: [
                .macOS(.v11),
                .iOS(.v11),
            ],
            products: [
                .library(name: "\(projectName)", targets: ["\(projectName)"]),
            ],
            targets: [
                .target(name: "\(projectName)"),
            \(withUnitTest
                ? "    .testTarget(name: \"\(projectName)Test\", dependencies: [\"\(projectName)\"])\n    ]"
                : "]")
        )
        """
    }
}
