# Select the export type from `swiftpm`, `cocoapods` or `sourcesOnly`. (Default: `swiftpm`)
exportType: swiftpm

# The path of output directory. (Default: `Dependencies`)
output: Dependencies

# In addition to environment variables, a properties file can be read.
envFile: .env

# Set the target according to the environment and other requirements that
# you want to use different build modes, etc.
targets:
  SecretKeysDebug:
    namespace: MySecretKeys
    keys:
      clientID:
        name: CLIENT_ID_DEBUG
      clientSecret:
        name: CLIENT_SECRET_DEBUG
      timeout:
        name: TIMEOUT_SECOUNDS

  SecretKeysProduction:
    namespace: MySecretKeys
    keys:
      clientID:
        name: CLIENT_ID_PRODUCTION
        config:
          DEBUG: CLIENT_ID_ADHOC
      clientSecret:
        name: CLIENT_SECRET_PRODUCTION
        config:
          DEBUG: CLIENT_SECRET_ADHOC
      timeout:
        name: TIMEOUT_SECOUNDS
