// DO NOT MODIFY
// Automatically generated by SecretKeys (https://github.com/simorgh3196/swift-secret-keys)

import XCTest
@testable import InstallationWithSPM

final class InstallationWithSPMTests: XCTestCase {
    func testKeysInDebug() throws {
        XCTAssertEqual(KeysInDebug.clientID, 12345)
        XCTAssertEqual(KeysInDebug.clientSecret, "abcde")
        XCTAssertEqual(KeysInDebug.timeout, 2.5)
    }

    func testKeysInRelease() throws {
        #if DEBUG
        XCTAssertEqual(KeysInRelease.clientID, 34567)
        XCTAssertEqual(KeysInRelease.clientSecret, "fghij")
        XCTAssertEqual(KeysInRelease.timeout, 2.5)
        #else
        XCTAssertEqual(KeysInRelease.clientID, 98765)
        XCTAssertEqual(KeysInRelease.clientSecret, "vWxYz")
        XCTAssertEqual(KeysInRelease.timeout, 2.5)
        #endif
    }
}
