name: SecretKeys

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  macos-run-tests-for-xcode14:
    name: Unit Tests Xcode 14.1
    runs-on: macos-12
    env:
      DEVELOPER_DIR: /Applications/Xcode_14.1.app/Contents/Developer
    steps:
      - uses: actions/checkout@v3
      - name: Run Tests for SecretKeys
        run: make test
      - name: Run Tests for command plugin example
        run: make test-for-command-plugin


  macos-run-tests-for-xcode13:
    name: Unit Tests 13.4.1
    runs-on: macos-12
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.4.1.app/Contents/Developer
    steps:
      - uses: actions/checkout@v3
      - name: Run Tests for SecretKeys
        run: make test

  discover-typos:
    name: Discover Typos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Discover typos
        run: |
          export PATH="$PATH:/Library/Frameworks/Python.framework/Versions/3.11/bin"
          python3 -m pip install --upgrade pip
          python3 -m pip install codespell
          codespell --ignore-words-list="hart,inout,msdos,sur" --skip="./.build/*,./Tests/GetTests/Mocker/*,./.git/*"

