name: SecretKeys

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  macos-run-tests:
    name: Unit Tests (Xcode ${{ matrix.xcode }})
    strategy:
      fail-fast: false
      matrix:
        xcode: ["14.1", "13.4.1"]
        include:
          - xcode: "14.1"
            macos: macOS-12
          - xcode: "13.4.1"
            macos: macOS-12
    runs-on: ${{ matrix.macos }}
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
    steps:
      - uses: actions/checkout@v3
      - name: Run Tests
        run: make test

  discover-typos:
    name: Discover Typos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Discover typos
        run: |
          export PATH="$PATH:/Library/Frameworks/Python.framework/Versions/3.11/bin"
          python3 -m pip install --upgrade pip
          python3 -m pip install codespell
          codespell --ignore-words-list="hart,inout,msdos,sur" --skip="./.build/*,./Tests/GetTests/Mocker/*,./.git/*"

